# Generated by Django 3.2.8 on 2021-10-22 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('linkedIn', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currName', models.CharField(max_length=255)),
                ('currDesc', models.CharField(max_length=255)),
                ('currImg', models.CharField(max_length=255)),
                ('currSource', models.CharField(blank=True, max_length=255)),
                ('currLink', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('gradDate', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PastProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastName', models.CharField(max_length=255)),
                ('pastDesc', models.CharField(max_length=255)),
                ('pastImg', models.CharField(max_length=255)),
                ('pastSource', models.CharField(blank=True, max_length=255)),
                ('pastLink', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projStatus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeUpdate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('dates', models.CharField(max_length=255)),
                ('jobDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Updated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyUpdate', models.CharField(max_length=255)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('updatedType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='app.updatetype')),
            ],
        ),
        migrations.CreateModel(
            name='AllProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projName', models.CharField(max_length=255)),
                ('projDesc', models.CharField(blank=True, max_length=255)),
                ('projSource', models.CharField(blank=True, max_length=255)),
                ('projLink', models.CharField(blank=True, max_length=255)),
                ('projOrg', models.CharField(blank=True, max_length=255)),
                ('theStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projStat', to='app.projectstatus')),
                ('theType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projTypes', to='app.projecttype')),
            ],
        ),
    ]
