# Generated by Django 3.2.8 on 2021-10-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprojects',
            name='theStatus',
            field=models.IntegerField(choices=[{'id': 0, 'status': 'Current'}, {'id': 1, 'status': 'Past'}], default=0),
        ),
        migrations.AlterField(
            model_name='allprojects',
            name='theType',
            field=models.IntegerField(choices=[{'id': 0, 'type': 'Front End'}, {'id': 1, 'type': 'Back End'}, {'id': 2, 'type': 'Full Stack'}, {'id': 3, 'type': 'Organization'}], default=0),
        ),
        migrations.AlterField(
            model_name='updated',
            name='updateType',
            field=models.IntegerField(choices=[{'id': 0, 'updateType': 'Current'}, {'id': 1, 'updateType': 'Past'}, {'id': 2, 'updateType': 'All'}, {'id': 3, 'updateType': 'Resume'}, {'id': 4, 'updateType': 'Contact'}], default=0),
        ),
    ]
