# Generated by Django 3.2.9 on 2021-11-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_currentproject_corder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastproject',
            name='pOrder',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
